# 下面两行是指明依赖库的来源地址
#source 'https://gitee.com/simonmiao/ATSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

# 说明平台是ios，版本是9.0
platform :ios, '9.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

# 针对MyApp target引入AFNetworking
# 针对MyAppTests target引入OCMock，
target 'iOSLearn' do 
    pod 'CYLTabBarController'
    pod 'UIAlertController+Blocks'
    pod 'AFNetworking', '~> 3.0' 
    pod 'Masonry'
    pod 'CocoaLumberjack'
    pod 'MJExtension'
    pod 'MJRefresh'
#    pod 'ATBase'
    pod 'YYKit'
    pod 'BGFMDB'
    pod 'UMCAnalytics'
    pod 'GTSDK'
    pod 'Aspects'
    # target 'MyAppTests' do
      # inherit! :search_paths 
      # pod 'OCMock', '~> 2.0.1' 
    # end
end
# 这个是cocoapods的一些配置,官网并没有太详细的说明,一般采取默认就好了,也就是不写.
post_install do |installer|       
   installer.pods_project.targets.each do |target| 
     puts target.name 
   end
end
